---
# Install iptables
- name: Install 
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - iptables-persistent
  - netfilter-persistent

# Configure
- name: Copy rules.v4 file
  template:
    src: rules.v4.j2
    dest: "/etc/iptables/rules.v4"
  notify: start netfilter-persistent
