---
# Install
- name: Add repo 
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C

- name: Install PHP
  apt:
    name: "php{{ php_version }}"
    state: present

- name: Install PHP extensions 
  apt:
    name: "php{{ php_version }}-{{ item }}"
    state: present
  with_items: "{{ php_extensions_ppa }}"

- name: Install PHP base packages
  apt:
    name: "php-{{ item }}"
    state: present
  with_items: "{{ php_base }}"

- name: download composer v1.8.5
  get_url:
    url: https://getcomposer.org/download/1.8.5/composer.phar
    dest: /usr/bin/composer.phar
    mode: '755'

- name: composer symlink
  file:
    src: /usr/bin/composer.phar
    dest: /usr/bin/composer
    state: link
