---
- name: Edit shell for user
  user:
    name: www-data
    shell: /bin/bash 

- name: mkdir
  file:
    path: "/var/www/.ssh/"
    state: directory

- name: ssh-keygen 
  openssh_keypair:
    path: /var/www/.ssh/id_rsa

- name: Change permission
  file:
    path: /var/www
    owner: www-data
    group: www-data
    recurse: yes
