---
- name: Check OS
  debug: var=ansible_os_family

- block:
  - name: Install epel-release
    yum:
      name: epel-release

  - name: Install nginx for RedHat
    yum:
      name: nginx
   
   when: ansible_os_family == "RedHat"
