---
- name: Check OS
  debug: var=ansible_os_family

- block:
  - name: Install epel-release
    yum:
      name: "{{ item }}"
    with_items: "{{ packages_redhat }}"

  - name: Start nginx
    service:
      name: nginx
      state: started
      enabled: yes 

  when: ansible_os_family == "RedHat"

- block:
  - name: Install nginx
    apt:
      name: "{{ item }}"
    with_items: "{{ packages_debian }}"

  - name: Start nginx
    service:
      name: nginx
      state: started
      enabled: yes

  when: ansible_os_family == "Debian"
