---
- name: Add an Apt signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    state: present
    filename: pgdg
    update_cache: yes

- name: Install postgresql
  apt:
    name: "postgresql-{{ postgresql_version }}"
    state: present
  notify: start postgresql

