---
# handlers file for php
- name: start services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
  - php7.1-fpm-2
  - php7.1-fpm-3
  - php7.1-fpm-4
  - php7.1-fpm-5

